/*
NAME:	XIAOYANG JU
ID:	7342138151
*/

CREATE TABLE STUDENTS(	personID	VARCHAR2(5),
						LOC	SDO_GEOMETRY,
						PRIMARY KEY(personID));

CREATE TABLE ANNOUNCEMENTSYSTEMS( 	asID	VARCHAR2(10),
									LOC		SDO_GEOMETRY,
									RADIUS	NUMBER,
									AREA	SDO_GEOMETRY,
									PRIMARY KEY(asID));

CREATE TABLE BUILDINGS(	buildingID	VARCHAR2(5),
						buildingNAME	VARCHAR2(50),
						NUM_VERTICES	NUMBER,
						LOC   			SDO_GEOMETRY,
						AREA 	 		SDO_GEOMETRY,
						PRIMARY KEY(buildingID));

insert into user_sdo_geom_metadata values('BUILDINGS','LOC',SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X',0,820,0.001),SDO_DIM_ELEMENT('Y',0,580,0.001)),null);
insert into user_sdo_geom_metadata values('BUILDINGS','AREA',SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X',0,820,0.001),SDO_DIM_ELEMENT('Y',0,580,0.001)),null);	
insert into user_sdo_geom_metadata values('STUDENTS','LOC',SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X',0,820,0.001),SDO_DIM_ELEMENT('Y',0,580,0.001)),null);
insert into user_sdo_geom_metadata values('ANNOUNCEMENTSYSTEMS','LOC',SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X',0,820,0.001),SDO_DIM_ELEMENT('Y',0,580,0.001)),null);
insert into user_sdo_geom_metadata values('ANNOUNCEMENTSYSTEMS','AREA',SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X',0,820,0.001),SDO_DIM_ELEMENT('Y',0,580,0.001)),null);

CREATE INDEX BUILDINGS_LOC_idx ON BUILDINGS(LOC) INDEXTYPE IS MDSYS.SPATIAL_INDEX;	
CREATE INDEX BUILDINGS_AREA_idx ON BUILDINGS(AREA) INDEXTYPE IS MDSYS.SPATIAL_INDEX;	
CREATE INDEX STUDENTS_idx ON STUDENTS(LOC) INDEXTYPE IS MDSYS.SPATIAL_INDEX;	
CREATE INDEX ANNOUNCEMENTSYSTEMS_LOC_idx ON ANNOUNCEMENTSYSTEMS(LOC) INDEXTYPE IS MDSYS.SPATIAL_INDEX;	
CREATE INDEX ANNOUNCEMENTSYSTEMS_AREA_idx ON ANNOUNCEMENTSYSTEMS(AREA) INDEXTYPE IS MDSYS.SPATIAL_INDEX;	