/*
NAME:	XIAOYANG JU
ID:	7342138151
*/
DELETE FROM user_sdo_geom_metadata;
DROP INDEX BUILDINGS_LOC_idx;
DROP INDEX BUILDINGS_AREA_idx;
DROP INDEX STUDENTS_idx;
DROP INDEX ANNOUNCEMENTSYSTEMS_LOC_idx;
DROP INDEX ANNOUNCEMENTSYSTEMS_AREA_idx;
DROP TABLE STUDENTS;
DROP TABLE ANNOUNCEMENTSYSTEMS;
DROP TABLE BUILDINGS;